import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// app/layout.tsx
import { Providers } from "./providers";
import App from "next/app";
import React from "react";
import Navbarr from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sotelius Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbarr />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
